---
output: 
  pdf_document: 
    keep_tex: true
bibliography: references.bib
---
# Présentation du contexte

## Cadre conceptuel de l'étude

Dans cette partie, nous allons définir certainses notions clés qui apparaissent dans notre étude : le taux de visite et la notion de voisin.

### Taux de visite

Le taux de visite n'est rien d'autre que le nombre moyen de visite dans chaque commune. IL est calculé en divisant le nombre de visite par la population de la commune en question. En d'autres termes, il s'agit du nombre de visites que chaque habitant de la commune a effectué en moyenne. 

$$\tau_i = \frac{n_i}{P_i}$$

où $\tau_i$ et $n_i$ sont respectivement le taux et le nombre de visite de la commune $i$. 

###  La notion de voisin

Il est indispensable de définir le voisinage d'un objet spatial pour quantifier l'influence réciproque entre entités. La définition formelle se traduit par la détermination d'un ensemble de couples \((i,j)\) d'objets spatiaux, avec la contrainte qu'un objet ne peut être voisin de lui-même, c'est-à-dire que pour tout \(i\), \((i,i)\) n'est pas considéré.

Une méthode classique consiste à construire une matrice de voisinage binaire \(W\) définie par :
$$
W_{ij} = \begin{cases} 
1, & \text{si } i \text{ et } j \text{ sont considérés comme voisins} \\
0, & \text{sinon}
\end{cases}
$$
Les méthodes pour définir les voisins sont diverses :
\begin{itemize}
  \item \textbf{Basée sur la distance :}  
  On utilise par exemple la distance euclidienne,
  $$
  d(i,j) = \sqrt{(x_i - x_j)^2 + (y_i - y_j)^2},
  $$
pour définir deux objets comme voisins si \(d(i,j)\) est inférieure à un seuil prédéfini, ou en pondérant cette distance par une fonction décroissante. Dans le cadre de cette étude, nous utiliserons la distance de Haversine, compte tenu des données utilisées (longitude et latitude)

\item \textbf{Basée sur la contiguïté :}  
  Pour des données surfaciques (comme des zones administratives), les voisins sont définis en fonction du partage d'une frontière commune. On distingue par exemple la contiguïté \emph{Rook} (deux zones sont voisines si elles partagent un segment de frontière) et la contiguïté \emph{Queen} (elles sont voisines si elles partagent au moins un point).
  
  \item \textbf{Basée sur l'optimisation d'une trajectoire :}  
  Une autre approche consiste à ordonner les points selon un chemin optimisé (par exemple, le plus court chemin ou le cycle hamiltonien dans le problème du voyageur de commerce). Les voisins d'un point sont alors définis comme les points qui se suivent immédiatement dans cet ordre.
\end{itemize}

###  Distance de Haversine

La distance de Haversine est une mesure de la distance entre deux points
sur une sphère, basée sur leurs coordonnées géographiques ($latitude$ et
$longitude$). Elle est particulièrement utile pour les données
géographiques projetées sur une surface sphérique, comme la Terre.

Si l'on considère deux points ($i$) et ($j$), la distance ($d_{ij}$)
entre ces deux points sur la surface d'une sphère de rayon ($r$) est
donnée par :

$$
 d_{ij} = 2r \cdot \arcsin\left(\sqrt{\sin^2\left(\frac{\phi_j - \phi_i}{2}\right) + \cos(\phi_i)\cos(\phi_j)\sin^2\left(\frac{\lambda_j - \lambda_i}{2}\right)}\right)
$$


Où : 

- $r$ : Rayon de la Terre (environ 6371 km).

-   $\phi_i, \phi_j$ : Latitudes des points $i$ et $j$ (en radians).

-   $\lambda_i, \lambda_j$ : Longitudes des points $i$ et $j$ (en radians). Après calcul nous avons ces statistiques sur nos distances.

## Revue de littérature

La modélisation des visites dans les hôpitaux est cruciale pour comprendre les dynamiques de la santé publique et optimiser la gestion des ressources médicales. En 2023, les services d'urgences en France ont enregistré environ 20,9 millions de passages, marquant une légère diminution par rapport à 2022 [@egora2023]. Parallèlement, l'accès aux consultations médicales spécialisées demeure préoccupant. En 2024, le délai moyen pour obtenir un rendez-vous chez un dermatologue était de 36 jours, l'un des plus longs parmi les spécialités médicales [@bfmtv2024]. Ces difficultés d'accès aux soins ont conduit un nombre croissant de patients à se tourner vers les services d'urgences pour des consultations non urgentes, accentuant ainsi la saturation de ces services. Dans ce contexte, il est crucial de comprendre les facteurs qui influencent le nombre de consultations médicales, afin d'allouer les ressources de manière optimale sur le plan matériel, humain et financier, tout en prévenant des situations de surcharge des établissements de santé.

De nombreuses études ont montré que le nombre de consultations médicales est influencé par une multitude de facteurs sociodémographiques, allant des caractéristiques individuelles aux contextes socio-économiques et territoriaux. L'âge est un déterminant majeur du recours aux soins. Les personnes âgées, en particulier celles de 65 à 79 ans, consultent plus fréquemment en raison de la prévalence accrue de maladies chroniques et du suivi médical nécessaire à leur prise en charge. En revanche, les jeunes adultes, en bonne santé, présentent une utilisation plus sporadique des services médicaux.

Le sexe constitue également un facteur différenciant : les femmes consultent plus fréquemment que les hommes, en raison de besoins spécifiques en santé reproductive et d'une plus grande propension à rechercher des soins préventifs. À l'inverse, les hommes, notamment dans les catégories socio-professionnelles les plus actives, tendent à sous-utiliser les services de soins, ce qui peut entraîner des diagnostics plus tardifs et des complications médicales accrues.

Le statut socio-économique et le niveau d'éducation influencent également de manière significative l'accès aux soins. Les individus à revenu élevé bénéficient généralement d'un meilleur accès aux consultations médicales, grâce à une couverture sociale plus complète et des assurances complémentaires qui allègent les coûts des soins. À l'inverse, les personnes en situation de précarité rencontrent des obstacles financiers, administratifs et culturels qui limitent leur recours aux soins, malgré des besoins souvent accrus en raison de conditions de vie plus précaires.

Le niveau d'éducation joue un rôle clé dans la fréquentation des services de santé. Une meilleure instruction est associée à une meilleure connaissance des risques sanitaires et à une adoption plus proactive des comportements de prévention, entraînant un recours plus fréquent aux soins médicaux. À l'inverse, un faible niveau d'éducation est souvent corrélé à un moindre suivi médical et à une utilisation plus tardive des services de soins, notamment en cas de complications.

La perception de la santé et l'accès géographique aux soins sont d'autres facteurs déterminants. Les individus qui jugent leur état de santé comme étant excellent ou très bon consultent moins fréquemment, tandis que ceux ayant une perception négative de leur état de santé sont plus enclins à multiplier les visites médicales [@statcan2022]. En ce qui concerne l'accès géographique, les inégalités spatiales jouent un rôle clé dans la fréquence des consultations. En milieu urbain, la densité médicale plus élevée facilite l'accès aux soins, tandis qu'en zones rurales ou médicalement sous-dotées, les délais d'attente et la distance à parcourir constituent des freins majeurs à l'accès aux soins [@irdes2020].

L'étude de Nkoua Mbon et al. (2021) sur les facteurs associés au faible niveau de fréquentation du centre de santé intégré de Pondila identifie plusieurs obstacles à la fréquentation, notamment le coût des soins, le mauvais état des routes, le chômage, le mauvais accueil par le personnel soignant et la non-disponibilité de médicaments. Ces facteurs soulignent la complexité de l'accès aux soins, notamment dans les zones plus rurales ou moins développées.

L'étude de Julie Dumouchel (2012) sur les pratiques des généralistes normands face aux urgences médicales met en évidence plusieurs éléments clés. Les facteurs organisationnels tels que la disponibilité des structures de soins, les horaires d'ouverture des cabinets et la collaboration avec d'autres professionnels de santé sont essentiels dans la gestion des urgences. Les facteurs personnels, notamment l'expérience professionnelle, la formation continue et la confiance en soi des médecins, jouent également un rôle crucial dans la prise en charge efficace des situations urgentes.

En outre, la présentation des patients, leur niveau d'urgence perçu et leurs attentes influencent la façon dont les médecins abordent les cas urgents. L'accès aux équipements médicaux, la qualité des infrastructures et la disponibilité des services d'urgence jouent aussi un rôle important. Cette étude met en lumière la complexité de la gestion des urgences en médecine générale, influencée par une série de facteurs interconnectés, et souligne la nécessité d'améliorer l'organisation des soins, de renforcer la formation des médecins et d'optimiser les ressources disponibles pour une gestion plus efficace des urgences médicales en Normandie.

L'un des facteurs pouvant influencer le nombre de consultations dans une zone est le renoncement aux soins  En effet, selon le rapport du DREES (Renoncement aux soins : la faible
densité médicale est un facteur aggravant pour les personnes pauvres), la question du renoncement aux soins dans les milieux urbains est influencée par une multitude de facteurs socio-économiques et structurels. Selon l'enquête Statistiques sur les ressources et conditions de vie (SRCV), une proportion significative de la population en France (3,1 %) renonce à des soins médicaux, un phénomène particulièrement prononcé chez les personnes pauvres qui vivent dans des zones à faible densité médicale. Ces individus sont jusqu'à huit fois plus susceptibles de renoncer aux soins en raison de l'accessibilité limitée à des médecins généralistes. 
