---
output: 
  pdf_document: 
    keep_tex: true
---

# Méthodologie

## Source des données

L’étude repose sur des données issues du Système National des Données de Santé (SNDS), couvrant la période 2018-2022 et portant sur environ 5000 communes. Ces données permettent d’analyser le nombre de consultations en médecine de ville en tenant compte des disparités territoriales et des caractéristiques locales.

Les informations utilisées concernent principalement le volume des consultations médicales et leur répartition géographique. Des données complémentaires sur le contexte communal, telles que la densité de population et l’accessibilité aux soins, permettent d’affiner l’analyse. L’intégration de ces éléments facilite une approche spatiale de la modélisation, essentielle pour détecter d’éventuelles inégalités d’accès aux soins.

L’ensemble des données a été anonymisé et traité conformément aux normes en vigueur, garantissant ainsi la confidentialité des informations exploitées. Cette base constitue une ressource précieuse pour mieux comprendre les dynamiques d’accès aux soins en médecine de ville et proposer des modèles adaptés aux spécificités territoriales.

## Justification de l'économétrie spatiale

L'économétrie spatiale est justifiée par des raisons économiques et économétriques. D’un point de vue économique, la proximité spatiale joue un rôle clé dans les décisions des agents économiques. Les entreprises, par exemple, ajustent leurs stratégies en fonction de la concurrence locale, tandis que la diffusion des innovations et les effets d'agglomération influencent la productivité régionale. Les externalités spatiales, telles que l’effet de pair et les interactions entre industries voisines, ont également un impact direct sur les marchés. Ainsi, la prise en compte de la dimension spatiale est essentielle pour comprendre les dynamiques économiques locales et globales.

Sur le plan économétrique, l’omission des effets spatiaux peut introduire des biais dans les estimations, rendant les modèles classiques inefficaces. L’autocorrélation spatiale des résidus (tout comme l'autocorrélation temporelle des résidus) est un problème récurrent, pouvant fausser l’inférence statistique si elle n'est pas correctement modélisée. De plus, l’hypothèse d’indépendance des observations, souvent supposée dans les modèles classiques, est rarement vérifiée lorsque des interactions spatiales existent. En intégrant des structures de dépendance spatiale, les modèles économétriques spatiaux permettent d'améliorer la précision des estimations et de mieux comprendre les relations entre unités géographiques, évitant ainsi les erreurs d’interprétation liées à des phénomènes locaux ou régionaux.

## Concepts fondamentaux en statistique spatiale

### Autocorrélation spatiale

L'autocorrélation spatiale désigne la dépendance statistique entre des observations géographiquement proches. En d'autres termes, les valeurs prises par une variable en un lieu donné sont influencées par les valeurs observées dans les localisations voisines. Cette dépendance peut être positive, lorsque des valeurs similaires se regroupent, ou négative, lorsqu’une valeur élevée en un point est associée à une valeur faible dans les zones environnantes.

### Diagramme de Moran

Le diagramme de Moran est un outil permettant d’analyser la structure spatiale d’une variable. Il représente un nuage de points où :  

- L’axe des abscisses affiche les valeurs centrées de la variable d’intérêt \( y \).  
- L’axe des ordonnées affiche les valeurs moyennes de cette variable pour les observations voisines \( W y \), où \( W \) est la matrice de poids normalisée.  

#### Interprétation  

En raison du centrage de \( y \) et de la normalisation de \( W \), la moyenne empirique de \( W y \) est égale à zéro.  

- **Si les observations sont distribuées aléatoirement dans l’espace**, il n’existe pas de relation particulière entre \( y \) et \( W y \). La pente de la droite de régression linéaire est alors proche de zéro, et les observations sont réparties de manière uniforme dans les quadrants.  
- **Si une structure spatiale existe**, la pente de la régression linéaire est différente de zéro, indiquant une corrélation entre \( y \) et \( W y \).  

Le diagramme est divisé en **quatre quadrants** définis par les lignes \( y = 0 \) et \( W y = 0 \), correspondant à différents types d’association spatiale :  

1. **Quadrant 1 (haut à droite, High-High)**  
   - Valeurs élevées de la variable \( y \) entourées par des valeurs également élevées.  
   - Indique une **autocorrélation spatiale positive**.  
   - Peut refléter des zones homogènes où les valeurs sont naturellement élevées.  

2. **Quadrant 3 (bas à gauche, Low-Low)**  
   - Valeurs faibles de \( y \) entourées par des valeurs également faibles.  
   - Indique une **autocorrélation spatiale positive**.  
   - Suggère la présence de zones où les valeurs sont homogènement basses.  

3. **Quadrant 2 (bas à droite, High-Low)**  
   - Valeurs élevées de \( y \) entourées par des valeurs faibles.  
   - Indique une **autocorrélation spatiale négative**.  
   - Peut signaler une hétérogénéité spatiale locale, où certaines observations diffèrent fortement de leur voisinage.  

4. **Quadrant 4 (haut à gauche, Low-High)**  
   - Valeurs faibles de \( y \) entourées par des valeurs élevées.  
   - Indique une **autocorrélation spatiale négative**.  
   - Peut traduire des zones de contraste spatial marquées.  

#### Utilité du Diagramme de Moran  

Le diagramme de Moran permet d’identifier les structures spatiales dominantes en observant la répartition des points dans les quadrants. Il aide également à détecter les observations atypiques qui s’écartent du modèle spatial général et à confirmer l’existence d’une autocorrélation spatiale en complément de l’indice de Moran, qui quantifie cette relation. Cet outil visuel est ainsi essentiel pour explorer la dépendance spatiale et comprendre les structures spatiales sous-jacentes d’une variable. 


### Matrice des poids spatiaux

Pour quantifier la proximité spatiale entre unités géographiques, on utilise une matrice de poids spatiaux notée $W$. Cette matrice représente les relations de voisinage et permet d’introduire la structure spatiale dans les modèles économétriques. La matrice de poids peut être une matrice de contiguité binaire ou peut tenir compte de la distance entre les zones géographiques. Cette étude utilise une matrice de poids basée sur la distance et contient des pondérations inversément proportionnelles à la distance entre les régions.

### Mesure de la corrélation spatiale

#### Indices de corrélation spatiale

L’un des indicateurs les plus couramment utilisés est l’indice de Moran. Il évalue la similitude des valeurs d’une variable entre différentes entités géographiques (par exemple, des communes) en
fonction de leur proximité spatiale. Il se base sur la matrice de poids
spatiale ($W$), qui définit les relations entre ces entités. Il se calcule comme suit :

$$
I = \frac{N}{\sum_{i} \sum_{j} W_{ij}} \times \frac{\sum_{i} \sum_{j} W_{ij} (y_i - \bar{y})(y_j - \bar{y})}{\sum_{i} (y_i - \bar{y})^2}
$$

où $y_i$ est la valeur de la variable d’intérêt en un point $i$, $\bar{y}$ est la moyenne de cette variable et $W_{ij}$ représente l’élément $(i, j)$ de la matrice de poids.

D'autres indices existent, comme la \textbf{statistique de Geary}, qui est moins sensible aux valeurs extrêmes, et les \textbf{indicateurs locaux d'autocorrélation spatiale (LISA)}, qui permettent d'identifier des clusters spatiaux spécifiques.

#### Construction de la matrice de poids

\
Pour construire la matrice de poids, nous avons alors suivi ces étapes.
\

1.  Calculer les distances de Haversine entre chaque paire d’entités.
2.  Définir un seuil de distance maximale ($d_{max}$) :
    -   Si $d_{ij} < d_{max}$, $w_{ij} = \frac{1}{d_{ij}}$.
    -   Sinon, $w_{ij} = 0$.
3.  Normaliser les poids pour que chaque ligne de la matrice ait une
    somme égale à 1 : $$
     w_{ij}^{norm} = \frac{w_{ij}}{\sum_{j} w_{ij}}.
    $$

#### Test significativité de l'indice de Moran :

Le test de significativité de l’indice de Moran permet d’évaluer si une variable présente une autocorrélation spatiale significative, c’est-à-dire si les valeurs observées dans des zones proches ont tendance à être similaires ou non.

\textbf{Hypothèses du test}

\begin{itemize}
    \item \textbf{Hypothèse nulle} \( H_0 \) : Il n’y a \textbf{pas d’autocorrélation spatiale} significative. Les valeurs observées sont distribuées de manière aléatoire dans l’espace.
    \item \textbf{Hypothèse alternative} \( H_1 \) : Il existe une \textbf{autocorrélation spatiale} significative (positive ou négative).
\end{itemize}

\textbf{Statistique de test}

L’Indice de Moran standardisé suit approximativement une distribution normale sous \( H_0 \). La statistique de test est donnée par :

$$
    Z = \frac{I - E(I)}{\text{Var}(I)}
$$

où :
\begin{itemize}
    \item \( I \) est l’Indice de Moran calculé sur les données,
    \item \( E(I) \) est l’espérance théorique de \( I \) sous \( H_0 \),
    \item \( \text{Var}(I) \) est la variance théorique de \( I \).
\end{itemize}

L’espérance sous \( H_0 \) pour un échantillon de taille \( n \) est donnée par :

$$
    E(I) = -\frac{1}{n - 1}
$$

\textbf{Règle de décision}

On compare la statistique \( Z \) à une loi normale centrée réduite \( \mathcal{N}(0,1) \). Pour un seuil de significativité \( \alpha \) (ex. 5 \%), on utilise les quantiles de la loi normale :

\begin{itemize}
    \item Si \( Z > z_{1-\alpha/2} \) ou \( Z < -z_{1-\alpha/2} \), on \textbf{rejette \( H_0 \)} et on conclut qu’il existe une autocorrélation spatiale significative.
    \item Si \( Z \in [-z_{1-\alpha/2}, z_{1-\alpha/2}] \), on \textbf{ne rejette pas \( H_0 \)}, et on considère que la distribution spatiale est aléatoire.
\end{itemize}

\textbf{Interprétation de l’Indice de Moran}

\begin{itemize}
    \item \( I > 0 \) et significatif : Autocorrélation spatiale \textbf{positive} (les zones proches ont des valeurs similaires).
    \item \( I < 0 \) et significatif : Autocorrélation spatiale \textbf{négative} (les zones proches ont des valeurs opposées).
    \item \( I \approx 0 \) et non significatif : Absence d’autocorrélation spatiale, les valeurs sont distribuées de manière aléatoire.
\end{itemize}

Ce test est couramment utilisé en analyse spatiale pour identifier des regroupements de valeurs similaires, par exemple dans les études de santé publique, d’aménagement du territoire ou d’économie régionale.

## Modélisation en économétrie spatiale

Voici un rappel des différents éléments utilisés dans l'ensemble des modèles d'économétrie spatiale :

\begin{itemize}
\item[\(Y\)] : Il s'agit du vecteur des observations de la variable dépendante, c'est-à-dire la variable que l'on cherche à expliquer (par exemple, le taux de visites, le taux de chômage, etc).
\item[\(X\)] : C'est la matrice des variables explicatives ou indépendantes. Elle regroupe toutes les caractéristiques observées qui sont supposées influencer \textbf{Y} (comme des variables socio-économiques, démographiques ou structurelles).
\item[\(\beta\)] : Ce vecteur de coefficients mesure l'effet direct des variables \textbf{X} sur la variable dépendante \textbf{Y}. Chaque coefficient indique l'impact d'une unité de variation dans la variable correspondante sur \textbf{Y}, en l'absence d'effets spatiaux.
\item[\(W\)] : La matrice des poids spatiaux définit la structure de voisinage entre les unités géographiques. Chaque élément \(W_{ij}\) quantifie l'influence ou la proximité de l'unité \(j\) par rapport à l'unité \(i\). Le choix de cette matrice (par contiguïté, distance, ou K plus proches voisins) est crucial car il détermine la manière dont l'information spatiale est intégrée dans le modèle.
\item[\(WY\)] : Le terme de décalage spatial de \textbf{Y}, obtenu par le produit de la matrice \textbf{W} par le vecteur \textbf{Y}. Il représente l'influence moyenne pondérée des valeurs de \textbf{Y} dans les zones voisines et permet de capturer la dépendance spatiale directe de la variable dépendante.
\item[\(WX\)] : Il s'agit du terme de décalage spatial des variables explicatives. Concrètement, il représente une version pondérée des variables \textbf{X} dans les zones voisines, où les pondérations sont définies par la matrice \textbf{W}. Ce terme permet de mesurer l'effet indirect (ou spillover) des caractéristiques des voisins sur \textbf{Y}.
\item[\(\varepsilon\)] : C'est le terme d'erreur classique, qui capture les influences non observées ou aléatoires sur \textbf{Y}. Il est généralement supposé être indépendant et identiquement distribué (iid).
\item[\(\rho\)] : Utilisé dans les modèles qui intègrent directement l'effet des valeurs voisines de \textbf{Y} (comme dans les modèles SAR et SDM). Ce paramètre mesure la force de l'interaction entre la valeur de \textbf{Y} d'une unité et les valeurs de \textbf{Y} des unités voisines. Un \(\rho\) positif indique une autocorrélation positive (les zones avec des valeurs élevées de \textbf{Y} tendent à être entourées de zones à valeurs élevées, et inversement).
\item[\(\lambda\)] : Spécifique au modèle SEM (Spatial Error Model), ce paramètre quantifie la corrélation spatiale présente dans le terme d'erreur. Il mesure l'influence des erreurs des unités voisines sur l'erreur de l'unité considérée, suggérant que des facteurs non observés présentent une structure spatiale.
\item[\(\theta\)] : Ce vecteur de coefficients est associé au terme \textbf{WX} et apparaît dans les modèles SDM et SLX. Il mesure l'effet des variables explicatives des zones voisines sur la variable dépendante \textbf{Y}, c'est-à-dire l'impact indirect des caractéristiques locales via leur diffusion spatiale.
\end{itemize}

### Modèles principaux

Le modèle général est défini comme suit :

$$
Y = \rho W Y + X \beta + \theta W X + u, \quad u = \lambda W u + \varepsilon
$$

\textbf{SAR (Spatial AutoRegressive Model)} :

Le modèle SAR introduit une dépendance spatiale directement sur la variable dépendante \( Y \). L'idée est que la valeur de \( Y \) en un lieu donné dépend des valeurs observées dans les zones voisines. Mathématiquement, il s'écrit :
$$
Y = \rho W Y + X \beta + \varepsilon
$$

\underline{\textbf{Interprétation :}}
\begin{itemize}
\item Si \( \rho > 0 \), les valeurs de \( Y \) ont tendance à être similaires entre voisins (autocorrélation positive).
\item Si \( \rho < 0 \), on observe un effet de dispersion, où les valeurs de \( Y \) sont opposées dans les zones voisines (autocorrélation négative).
\item Si \( \rho = 0 \), il n’y a pas de dépendance spatiale, et le modèle classique de régression linéaire est suffisant.
\end{itemize}

\textbf{SEM (Spatial Error Model)} :

Le modèle SEM est utilisé lorsque la dépendance spatiale affecte les erreurs du modèle plutôt que la variable dépendante elle-même. Il est défini par :
$$
Y = X \beta + u, \quad u = \lambda W u + \varepsilon
$$
\underline{\textbf{Interprétation :}}
\begin{itemize}
\item Contrairement au modèle SAR, le modèle SEM suppose que la dépendance spatiale est un effet de perturbation, provenant d’omissions de variables pertinentes qui suivent une structure spatiale.
\item Il est utilisé lorsque la corrélation spatiale détectée dans un modèle classique provient d’erreurs spatialement autocorrélées, plutôt que d’une interaction directe entre observations.
\end{itemize}

\textbf{SLX (Spatial Lag of X Model)} :

Le modèle SLX est plus facile à estimer, car il suppose que la variable dépendante \( Y \) n’est pas directement influencée par les valeurs voisines, mais uniquement par les variables explicatives des zones voisines. Il est écrit comme suit :
$$
Y = X \beta + \theta W X + \varepsilon
$$
où \( W X \) capture l'effet des variables explicatives des unités voisines.

\underline{\textbf{Interprétation :}}
\begin{itemize}
\item Il n’y a pas d’effet direct des valeurs voisines de \( Y \).
\item Il mesure uniquement l'effet de "spillover" (d'effet de débordement) des facteurs explicatifs.
\end{itemize}

\textbf{SDM (Spatial Durbin Model)} :

Le modèle SDM est une extension du modèle SAR. Il prend en compte non seulement la dépendance de \( Y \) aux observations voisines, mais aussi l'effet des variables explicatives des régions voisines. Il est défini par :
$$
Y = \rho W Y + X \beta + \theta W X + \varepsilon
$$
\underline{\textbf{Interprétation :}}

\begin{itemize}
\item Si \( \theta = 0 \), le modèle SDM devient un SAR classique.
\item Si \( \rho = 0 \), il devient un modèle SLX (voir ci-dessous).
\item Il permet de tester si des variables exogènes influencent \( Y \) au-delà des frontières administratives.
\end{itemize}

\textbf{Comparaison des modèles}

\begin{table}[h]
    \centering
    \begin{tabular}{|l|c|c|c|}
        \hline
        \textbf{Modèle} & \textbf{Dépendance spatiale sur \( Y \)} & \textbf{Effet des \( X \) des voisins} & \textbf{Effet des erreurs} \\
        \hline
        \textbf{SAR}  & Oui  & Non  & Non \\
        \hline
        \textbf{SEM}  & Non  & Non  & Oui \\
        \hline
        \textbf{SLX}  & Non  & Oui  & Non \\
        \hline
        \textbf{SDM}  & Oui  & Oui  & Non \\
        \hline
    \end{tabular}
    \caption{Comparaison des modèles spatiaux}
    \label{tab:comparaison_modeles}
\end{table}