project:
  type: book
book:
  title: "Modélisation du nombre de consultations en médecine de ville en tenant compte des 
caractéristiques des villes et de la spatialisation : approche par modèle mixte"
  author: "Groupe 25"
  date: "Janvier 2025"
  chapters:
    - index.qmd
    - introduction.qmd
    - methodologie.qmd
    - analyse_descriptive.qmd
    - modelisation.qmd
    - conclusion.qmd

bibliography: references.bib

format: 
  pdf: 
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
    keep-tex: true
    bibliography: mabiblio.bib
    cite-method: natbib
  docx: default



