project:
  type: book
book:
  chapters:
    - index.qmd
    - introduction.qmd
    - concept_revue.qmd
    - methodologie.qmd
    - analyse_descriptive.qmd
    - modelisation.qmd
    - conclusion.qmd
    - bibliographie.qmd
  downloads: [pdf, epub] 

bibliography: references.bib

format: 
  pdf: 
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 4
    keep-tex: true